### ISSUE TITLE
`Function` is incorrectly wrapped

### ISSUE THREAD

**Issue by ljharb** [substack/coverify#20]
In `es5-shim`, which is used in tests by a number of my modules, I do `var call = Function.prototype.call;`. However, when run under `covert`, `Function` isn't actually the standard builtin - instead, it's a coverify-wrapped function.

This would be fine, except that all of the expected properties are not copied to the wrapped function: `prototype`, `call`, `bind`, etc.

I'm not sure what a solution is here, but I've had to disable usage of `covert` in order to avoid test failure.

**Comment by substack** [comment]
Fixed in 1.4.1.

**Comment by ljharb** [comment]
Thanks!! \\( ﾟ◡ﾟ)/
